# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.organ.com:
    container_name: orderer.organ.com
    image: hyperledger/fabric-orderer
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/organ.com/orderers/orderer.organ.com/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/organ.com/orderers/orderer.organ.com/tls/:/var/hyperledger/orderer/tls
    - orderer.organ.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.hospital.organ.com:
    container_name: peer0.hospital.organ.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.hospital.organ.com
      - CORE_PEER_ADDRESS=peer0.hospital.organ.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.hospital.organ.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.hospital.organ.com:7051
      - CORE_PEER_LOCALMSPID=HospitalMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/hospital.organ.com/peers/peer0.hospital.organ.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/hospital.organ.com/peers/peer0.hospital.organ.com/tls:/etc/hyperledger/fabric/tls
        - peer0.hospital.organ.com:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053

  peer1.hospital.organ.com:
    container_name: peer1.hospital.organ.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.hospital.organ.com
      - CORE_PEER_ADDRESS=peer1.hospital.organ.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.hospital.organ.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.hospital.organ.com:7051
      - CORE_PEER_LOCALMSPID=HospitalMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/hospital.organ.com/peers/peer1.hospital.organ.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/hospital.organ.com/peers/peer1.hospital.organ.com/tls:/etc/hyperledger/fabric/tls
        - peer1.hospital.organ.com:/var/hyperledger/production

    ports:
      - 8051:7051
      - 8053:7053

  peer0.histocompatibility.organ.com:
    container_name: peer0.histocompatibility.organ.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.histocompatibility.organ.com
      - CORE_PEER_ADDRESS=peer0.histocompatibility.organ.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.histocompatibility.organ.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.histocompatibility.organ.com:7051
      - CORE_PEER_LOCALMSPID=HLMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/histocompatibility.organ.com/peers/peer0.histocompatibility.organ.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/histocompatibility.organ.com/peers/peer0.histocompatibility.organ.com/tls:/etc/hyperledger/fabric/tls
        - peer0.histocompatibility.organ.com:/var/hyperledger/production
    ports:
      - 9051:7051
      - 9053:7053

  peer1.histocompatibility.organ.com:
    container_name: peer1.histocompatibility.organ.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.histocompatibility.organ.com
      - CORE_PEER_ADDRESS=peer1.histocompatibility.organ.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.histocompatibility.organ.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.histocompatibility.organ.com:7051
      - CORE_PEER_LOCALMSPID=HLMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/histocompatibility.organ.com/peers/peer1.histocompatibility.organ.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/histocompatibility.organ.com/peers/peer1.histocompatibility.organ.com/tls:/etc/hyperledger/fabric/tls
        - peer1.histocompatibility.organ.com:/var/hyperledger/production
    ports:
      - 10051:7051
      - 10053:7053

  peer0.opo.organ.com:
    container_name: peer0.opo.organ.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.opo.organ.com
      - CORE_PEER_ADDRESS=peer0.opo.organ.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.opo.organ.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.opo.organ.com:7051
      - CORE_PEER_LOCALMSPID=OPOMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/opo.organ.com/peers/peer0.opo.organ.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/opo.organ.com/peers/peer0.opo.organ.com/tls:/etc/hyperledger/fabric/tls
        - peer0.opo.organ.com:/var/hyperledger/production
    ports:
      - 11051:7051
      - 11053:7053

  peer1.opo.organ.com:
    container_name: peer1.opo.organ.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.opo.organ.com
      - CORE_PEER_ADDRESS=peer1.opo.organ.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.opo.organ.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.opo.organ.com:7051
      - CORE_PEER_LOCALMSPID=OPOMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/opo.organ.com/peers/peer1.opo.organ.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/opo.organ.com/peers/peer1.opo.organ.com/tls:/etc/hyperledger/fabric/tls
        - peer1.opo.organ.com:/var/hyperledger/production
    ports:
      - 12051:7051
      - 12053:7053

  peer0.gp.organ.com:
    container_name: peer0.gp.organ.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.gp.organ.com
      - CORE_PEER_ADDRESS=peer0.gp.organ.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.gp.organ.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.gp.organ.com:7051
      - CORE_PEER_LOCALMSPID=GPMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/gp.organ.com/peers/peer0.gp.organ.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/gp.organ.com/peers/peer0.gp.organ.com/tls:/etc/hyperledger/fabric/tls
        - peer0.gp.organ.com:/var/hyperledger/production
    ports:
      - 13051:7051
      - 13053:7053

  peer1.gp.organ.com:
    container_name: peer1.gp.organ.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.gp.organ.com
      - CORE_PEER_ADDRESS=peer1.gp.organ.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.gp.organ.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.gp.organ.com:7051
      - CORE_PEER_LOCALMSPID=GPMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/gp.organ.com/peers/peer1.gp.organ.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/gp.organ.com/peers/peer1.gp.organ.com/tls:/etc/hyperledger/fabric/tls
        - peer1.gp.organ.com:/var/hyperledger/production
    ports:
      - 14051:7051
      - 14053:7053