NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.hospital.organ.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.hospital.organ.com-cert.pem
    OrganizationalUnitIdentifier: peer
